prenom = input("Quel est ton prénom ?")
age = input("Tu as quel age ?")
pays = input("Quel est ton pays ?")
métier = input("Quel est ton métier de rêves ?")
print()
print("===== MA CARTE D'IDENTITÉ =====")
print("Prénom :" , prenom)
print("Age :" , age)
print("Pays :" , pays)
print("Métier de rêves :" , métier)